baseURL = "https://danohn.com/"
locale = "en-us"
title = "danohn.com"
enableRobotsTXT = true

[params]
  description = "Engineering notes from the things I’m building and learning."
  author = "Daniel"
  socialImage = ""

[params.social]
  github = "https://github.com/danohn"
  x = "https://x.com/dan_ohn"
  linkedin = "https://www.linkedin.com/in/dohnesorge/"

[params.analytics]
  plausibleScript = "https://analytics.danohn.com/js/pa-y0g4-do_o7Mkl5zAZtMND.js"

[params.giscus]
  repo = "danohn/danohn.com"
  repoId = "R_kgDOSxo24w"
  category = "Comments"
  categoryId = "DIC_kwDOSxo2484C-i1-"

[taxonomies]
  topic = "topics"

[markup]
  [markup.highlight]
    noClasses = false
    style = "github"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 20
